// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Home → Agenda*
 */
export interface PageDocumentDataAgendaItem {
  /**
   * Agente field in *Home → Agenda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].agente
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  agente: prismic.KeyTextField;

  /**
   * Ano field in *Home → Agenda*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].ano
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  ano: prismic.SelectField<"2025" | "2026" | "2027" | "2029" | "2030">;

  /**
   * Mês field in *Home → Agenda*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].mes
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  mes: prismic.SelectField<
    | "Janeiro"
    | "Feveiro"
    | "Março"
    | "Abril"
    | "Maio"
    | "Junho"
    | "Julho"
    | "Agosto"
    | "Setembro"
    | "Otubro"
    | "Novembro"
    | "Dezembro"
  >;

  /**
   * Data Inicial field in *Home → Agenda*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].data_inicial
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  data_inicial: prismic.SelectField<
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "9"
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16"
    | "17"
    | "18"
    | "19"
    | "20"
    | "21"
    | "22"
    | "23"
    | "24"
    | "25"
    | "26"
    | "27"
    | "28"
    | "29"
    | "30"
    | "31"
    | "8"
  >;

  /**
   * Data Final field in *Home → Agenda*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].data_final
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  data_final: prismic.SelectField<
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16"
    | "17"
    | "18"
    | "19"
    | "20"
    | "21"
    | "22"
    | "23"
    | "24"
    | "25"
    | "26"
    | "27"
    | "28"
    | "29"
    | "30"
    | "31"
  >;

  /**
   * Horas field in *Home → Agenda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].horas
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horas: prismic.KeyTextField;

  /**
   * Distrito field in *Home → Agenda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].distrito
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  distrito: prismic.KeyTextField;

  /**
   * Localidade field in *Home → Agenda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].localidade
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  localidade: prismic.KeyTextField;

  /**
   * Tipo field in *Home → Agenda*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].tipo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tipo: prismic.SelectField<"Residências" | "Obras" | "Mediação">;

  /**
   * Título field in *Home → Agenda*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *Home → Agenda*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Local field in *Home → Agenda*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[].local
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  local: prismic.RichTextField;
}

/**
 * Item in *Home → Apoios*
 */
export interface PageDocumentDataApoiosItem {
  /**
   * Local field in *Home → Apoios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].local
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  local: prismic.KeyTextField;

  /**
   * Texto field in *Home → Apoios*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].texto
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto: prismic.RichTextField;

  /**
   * Texto 2 field in *Home → Apoios*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].texto_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_2: prismic.RichTextField;

  /**
   * Imagem 1 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_1: prismic.ImageField<never>;

  /**
   * Imagem 2 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_2: prismic.ImageField<never>;

  /**
   * Imagem 3 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_3: prismic.ImageField<never>;

  /**
   * Imagem 4 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_4: prismic.ImageField<never>;

  /**
   * Imagem 5 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_5: prismic.ImageField<never>;

  /**
   * Imagem 6 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_6: prismic.ImageField<never>;

  /**
   * Imagem 7 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_7
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_7: prismic.ImageField<never>;

  /**
   * Imagem 8 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_8
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_8: prismic.ImageField<never>;

  /**
   * Imagem 9 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_9
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_9: prismic.ImageField<never>;

  /**
   * Imagem 10 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_10
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_10: prismic.ImageField<never>;

  /**
   * Imagem 11 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_11
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_11: prismic.ImageField<never>;

  /**
   * Imagem 12 field in *Home → Apoios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[].imagem_12
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_12: prismic.ImageField<never>;
}

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface PageDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Bio field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Agenda field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.agenda[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  agenda: prismic.GroupField<Simplify<PageDocumentDataAgendaItem>>;

  /**
   * Apoios field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.Apoios[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Apoios: prismic.GroupField<Simplify<PageDocumentDataApoiosItem>>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

interface UidDocumentData {}

/**
 * uid document from Prismic
 *
 * - **API ID**: `uid`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UidDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<UidDocumentData>, "uid", Lang>;

export type AllDocumentTypes = PageDocument | UidDocument;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataAgendaItem,
      PageDocumentDataApoiosItem,
      PageDocumentDataSlicesSlice,
      UidDocument,
      UidDocumentData,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
