// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = AgendaSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Agenda → Default → Primary → Evento*
 */
export interface AgendaSliceDefaultPrimaryEventoItem {
  /**
   * Cor field in *Agenda → Default → Primary → Evento*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.evento[].cor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cor: prismic.SelectField<"Laranja" | "Rosa" | "Amarelo">;

  /**
   * Datas field in *Agenda → Default → Primary → Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.evento[].datas
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  datas: prismic.KeyTextField;

  /**
   * Nome field in *Agenda → Default → Primary → Evento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.evento[].nome
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome: prismic.RichTextField;

  /**
   * Tipo field in *Agenda → Default → Primary → Evento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.evento[].tipo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tipo: prismic.KeyTextField;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Evento field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.evento[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  evento: prismic.GroupField<Simplify<AgendaSliceDefaultPrimaryEventoItem>>;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AgendaSlice,
      AgendaSliceDefaultPrimaryEventoItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
