// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  full_width_image: dynamic(() => import("./Carrossel")),
  quote: dynamic(() => import("./Quote")),
  two_column_text: dynamic(() => import("./TwoColumnText")),
};
