// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  agenda: dynamic(() => import("./Agenda")),
  rich_text: dynamic(() => import("./RichText")),
};
